### ISSUE TITLE
State badge does not work anymore since 0.88

### ISSUE THREAD

**Issue by jncanches** [andrey-git/home-assistant-custom-ui#169] opened 2019-02-21 14:17 UTC
Since State badge has been converted to TypeScript [(link to commit),](https://github.com/home-assistant/home-assistant-polymer/pull/2712) icon_color in templates does not work anymore

The problem is that hooks.js redefine _updateIconAppearance function of StateBadge custom element but it does not exists anymore. I think that now, the function to override now is updated()

**Comment by jncanches** [comment] 2019-02-21 14:18
Same problem as issue 168

**Comment by andrey-git** [comment] 2019-03-24 08:44
Duplicate of #168

**Closed by andrey-git** 2019-03-24 08:44 UTC
