### ISSUE TITLE
Brightness slider no longer auto updating

### ISSUE THREAD

**Issue by mihalski** [andrey-git/home-assistant-custom-ui#9] opened 2017-05-10 10:34 UTC
I'm not sure as of which version of HA this happened (I'm currently running 0.44.0) but the brightness slider doesn't update based on the brightness of the light. I can still manually chang it but if it is changed by an automation or another mechanism it does not update.

![screen shot 2017-05-10 08 28 09 pm](https://cloud.githubusercontent.com/assets/3755059/25894647/fb91a152-35bf-11e7-8b46-26974935e40e.png)

**Comment by andrey-git** [comment] 2017-05-11 05:50
Are you using the latest custom ui?
I made an unrelated fix today. Could you try to upgrade?

Any errors in browser dev console?

**Comment by mihalski** [comment] 2017-05-11 09:40
I just updated all the files and restarted Home Assistant. Still the same behaviour and I cannot see any errors or even warning in the dev console. I am using the current version of Safari on macOS Sierra.

Same behaviour in Chrome. I'm certain that it used to work.

**Comment by andrey-git** [comment] 2017-05-11 10:17
I just tried it using www.browserstack.com on Chrome 58 on MacOS Sierra. Everything worked fine.

Could you try to do the same (this setup is free) so that we know whether the problem is browser-specific or specific to your machine.

**Comment by mihalski** [comment] 2017-05-11 10:42
Still the same problem. So specific to my machine.

**Comment by andrey-git** [comment] 2017-05-11 10:52
In Chrome dev console tick the 'disable cache' box and reload. What files do you see in sources tab under `local/custom_ui`?

Also try to run Home Assistant in development mode:
```
http:
  development: 1
```
Any changes?

**Comment by mihalski** [comment] 2017-05-11 11:17
None of those things made any difference, and these were the files loaded:
![screen shot 2017-05-11 09 00 00 pm](https://cloud.githubusercontent.com/assets/3755059/25946447/8341b2da-368e-11e7-9e1d-2caa8a4dcfd3.png)
HOWEVER, I did notice that the custom_ui slider is treating the value of the light when it is turned on as if it were the max brightness.

Now all of a sudden HA is giving me this error:
```
Home Assistant had trouble
connecting to the server.

TRY AGAIN
```
First time I've ever sen it and it may have something to do with that development mode.

**Comment by mihalski** [comment] 2017-05-11 11:34
I just watched an automation fire where the Family Room Lamp (comprised of 2 lights) goes to 1/3 brightness for 5 minutes before turning off.

The sliders did not drop when it did this (the bulb icons darkened). I remember in particular that this always worked as I've seen it happen many times. Of course if you then click on the light it shows the correct position of the slider within the info window.

So the problem stands as it originally did plus there's the max brightness being redefined for some lights (possibly based off initial power on brightness).

**Comment by andrey-git** [comment] 2017-05-11 12:38
Could you share the customize-related part of your config?

Can you explain what do you mean by 
> custom_ui slider is treating the value of the light when it is turned on as if it were the max brightness.

**Comment by mihalski** [comment] 2017-05-11 13:09
```
  customize_glob:
    light.*:
      custom_ui_state_card: custom_light
      state_card_mode: break-slider
      stretch_slider: true
```
So the light has been set to say 30% and turned off.. It remembers it's brightness (lifx). I now turn on the light and the custom_ui thinks that it's at 100% but the info panel when you click on the light is aware that it's actually at 30%.

**Comment by andrey-git** [comment] 2017-05-11 13:46
I have added debug printouts to a new `debug` branch:
https://github.com/andrey-git/home-assistant-custom-ui/tree/debug

Could you refetch `ha-themed-slider.html` and `state-card-with-slider.html` from there, test again and put here the printouts from dev console?

I'm interested in what happens when you change the value externally (for example via the slider in the popup window).

**Comment by mihalski** [comment] 2017-05-11 21:39
With the help of the debug files I was able to solve the problem. The custom_ui assumes a maximum brightness of 100 (even though instructions seem to imply 255). Setting a value of 255 fixes the problem. The issue was that then the value was changed to anything above 100 the slider would not update since 100 was its maximum value.

Thank you for your help!

**Comment by andrey-git** [comment] 2017-05-12 05:51
This wasn't supposed to happen. LIght should be 0..255 by default. Cover should be 0..100 by default.

What config changed fixed this for you?

**Comment by mihalski** [comment] 2017-05-12 08:18
All I did was add:
```
slider_theme:
        min: 0
        max: 255
        pin: true
```

**Comment by andrey-git** [comment] 2017-05-12 13:22
I would like to find the bug so that I can fix the default behavior.

I have added more debug printouts to `ha-themed-slider.html` and `state-card-with-slider.html`. in the **debug** branch.

Could you get them, remove the `slider_theme`, tests again and post the printouts?

Note that I pushed a new incompatible version to the master branch, but I would like to fix this bug before I announce it.

**Comment by mihalski** [comment] 2017-05-14 10:45
I don't know how to explain this.. But using your debug versions it works even without the slider_theme.

**Comment by mihalski** [comment] 2017-05-14 11:22
And now it's not working again.. I don't know what's going on. No changes except for playing around with groups.

**Comment by mihalski** [comment] 2017-05-14 11:31
Is there a specific series of steps you'd like me to take when the lights set themselves to max 100 instead of 255 that would help you create a meaningful javascript log?

**Comment by andrey-git** [comment] 2017-05-14 12:33
Jut put here (or at hastebin.com) the log and tell me at which point you did what and at which point did you observed the wrong behavior.

The log is auto-cleaned on page reload, don't clean it otherwise so I can see the whole "progress".

**Comment by mihalski** [comment] 2017-05-14 13:26
Seems a little easier to do this way. I just focused on the things which should highlight the problem.
![screen shot 2017-05-14 11 19 24 pm](https://cloud.githubusercontent.com/assets/3755059/26034220/c18d99ee-38fc-11e7-8177-d7861d91511a.png)
If you'd like something more specific let me know.

**Comment by mihalski** [comment] 2017-05-14 13:28
Would it be possible for the debug to print out the max and min values?

**Comment by andrey-git** [comment] 2017-05-14 17:45
Yes, the problem seems to be with the mix/max values.

This seems to be generated using the 1st version of the debug prints. In the 2nd version I added min/max printouts which I don't see here. I fix a syntax error in the debug version, could you download and retry?

**Comment by mihalski** [comment] 2017-05-14 21:36
Strange as I only just downloaded the files from the debug branch before I posted that. Filesizes are different (orig being original, debug1 being the original debug files and the files in situ being the updated debug files):
```
(homeassistant_venv) homeassistant@homepi:~/.homeassistant/www/custom_ui$ ls -l
total 80
-rw-r--r-- 1 homeassistant homeassistant  248 May 11 15:47 CHANGELOG.md
-rw-r--r-- 1 homeassistant homeassistant  577 May 11 15:47 dynamic-element.html
-rw-r--r-- 1 homeassistant homeassistant 3154 May 11 15:47 dynamic-with-extra.html
-rw-r--r-- 1 homeassistant homeassistant 3756 May 14 18:11 ha-themed-slider.html
-rw-r--r-- 1 homeassistant homeassistant 3534 May 12 07:17 ha-themed-slider.html_debug1
-rw-r--r-- 1 homeassistant homeassistant 3334 May 11 15:47 ha-themed-slider.html_orig
-rw-r--r-- 1 homeassistant homeassistant 1067 May 11 15:47 LICENSE
-rw-r--r-- 1 homeassistant homeassistant  704 May 11 15:47 package.json
-rw-r--r-- 1 homeassistant homeassistant 5593 May 11 15:47 README.md
-rw-r--r-- 1 homeassistant homeassistant  877 May 11 15:47 state-card-custom_cover.html
-rw-r--r-- 1 homeassistant homeassistant  948 May 11 15:47 state-card-custom_light.html
-rw-r--r-- 1 homeassistant homeassistant 8805 May 14 18:13 state-card-with-slider.html
-rw-r--r-- 1 homeassistant homeassistant 8720 May 12 07:18 state-card-with-slider.html_debug1
-rw-r--r-- 1 homeassistant homeassistant 8118 May 11 15:47 state-card-with-slider.html_orig
(homeassistant_venv) homeassistant@homepi:~/.homeassistant/www/custom_ui$ mv ha-themed-slider.html ha-themed-slider.html_debug2
(homeassistant_venv) homeassistant@homepi:~/.homeassistant/www/custom_ui$ mv state-card-with-slider.html state-card-with-slider.html_debug2
(homeassistant_venv) homeassistant@homepi:~/.homeassistant/www/custom_ui$ wget https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/debug/ha-themed-slider.html
--2017-05-15 07:31:13--  https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/debug/ha-themed-slider.html
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.96.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.96.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3756 (3.7K) [text/plain]
Saving to: ‘ha-themed-slider.html’

ha-themed-slider.html                 100%[===========================================================================>]   3.67K  --.-KB/s   in 0.002s 

2017-05-15 07:31:13 (2.06 MB/s) - ‘ha-themed-slider.html’ saved [3756/3756]

(homeassistant_venv) homeassistant@homepi:~/.homeassistant/www/custom_ui$ wget https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/debug/state-card-with-slider.html
--2017-05-15 07:31:57--  https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/debug/state-card-with-slider.html
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.96.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.96.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8805 (8.6K) [text/plain]
Saving to: ‘state-card-with-slider.html’

state-card-with-slider.html           100%[===========================================================================>]   8.60K  --.-KB/s   in 0.004s 

2017-05-15 07:31:58 (1.93 MB/s) - ‘state-card-with-slider.html’ saved [8805/8805]

(homeassistant_venv) homeassistant@homepi:~/.homeassistant/www/custom_ui$ ls -l
total 96
-rw-r--r-- 1 homeassistant homeassistant  248 May 11 15:47 CHANGELOG.md
-rw-r--r-- 1 homeassistant homeassistant  577 May 11 15:47 dynamic-element.html
-rw-r--r-- 1 homeassistant homeassistant 3154 May 11 15:47 dynamic-with-extra.html
-rw-r--r-- 1 homeassistant homeassistant 3756 May 15 07:31 ha-themed-slider.html
-rw-r--r-- 1 homeassistant homeassistant 3534 May 12 07:17 ha-themed-slider.html_debug1
-rw-r--r-- 1 homeassistant homeassistant 3756 May 14 18:11 ha-themed-slider.html_debug2
-rw-r--r-- 1 homeassistant homeassistant 3334 May 11 15:47 ha-themed-slider.html_orig
-rw-r--r-- 1 homeassistant homeassistant 1067 May 11 15:47 LICENSE
-rw-r--r-- 1 homeassistant homeassistant  704 May 11 15:47 package.json
-rw-r--r-- 1 homeassistant homeassistant 5593 May 11 15:47 README.md
-rw-r--r-- 1 homeassistant homeassistant  877 May 11 15:47 state-card-custom_cover.html
-rw-r--r-- 1 homeassistant homeassistant  948 May 11 15:47 state-card-custom_light.html
-rw-r--r-- 1 homeassistant homeassistant 8805 May 15 07:31 state-card-with-slider.html
-rw-r--r-- 1 homeassistant homeassistant 8720 May 12 07:18 state-card-with-slider.html_debug1
-rw-r--r-- 1 homeassistant homeassistant 8805 May 14 18:13 state-card-with-slider.html_debug2
-rw-r--r-- 1 homeassistant homeassistant 8118 May 11 15:47 state-card-with-slider.html_orig
(homeassistant_venv) homeassistant@homepi:~/.homeassistant/www/custom_ui$ 
```
 Same process followed except we're starting with the 98 brightness the light was left at yesterday. Still no min/max debugs:
![screen shot 2017-05-15 07 34 30 am](https://cloud.githubusercontent.com/assets/3755059/26037926/1bf6ad14-3941-11e7-9b97-6e3205d9bcb2.png)

**Comment by andrey-git** [comment] 2017-05-15 19:17
In the network tab check that caching is disabled.

**Comment by mihalski** [comment] 2017-05-15 21:32
This is what it has been since you asked me to change it:
![screen shot 2017-05-16 07 31 48 am](https://cloud.githubusercontent.com/assets/3755059/26080410/cb9bdb5e-3a09-11e7-881a-7b34e6e0c835.png)

**Comment by andrey-git** [comment] 2017-05-16 06:07
Weird...
Do you connect to HA directly or maybe you have some proxy in between?

Another thing to try:
In Chrome settings -> Content settings -> All cookies and site data -> type in your HA url => Delete everything.

**Comment by mihalski** [comment] 2017-05-16 08:29
No proxies. I tried your suggestion but it made no difference.

How does the code decide what the max setting for the slider is?

**Comment by blackgearit** [comment] 2017-05-16 08:33
I have similar issue with my cover.
The slider on the main view is at position 0, but when i click on the cover name, the popup panel slider is set to the real value.
More, if i set the cover position from the slider on the main view, it displays the right position until i reload the page.

No proxy and no cookies. Disable cache checked in dev tools.

**Comment by mihalski** [comment] 2017-05-16 09:04
Have you tried adding a slider theme with the appropriate min/max values to see if that resolves the problem?

**Comment by blackgearit** [comment] 2017-05-16 09:50
@mihalski  adding
```
slider_theme:
        min: 0
        max: 100
        pin: true
```
did not solve the problem

**Comment by mihalski** [comment] 2017-05-16 10:04
Are you sure the max value is 100?

**Comment by blackgearit** [comment] 2017-05-16 10:07
@mihalski here it is

![image](https://cloud.githubusercontent.com/assets/8858847/26101075/2b454eac-3a30-11e7-8d10-5eb74440f24e.png)

**Comment by mihalski** [comment] 2017-05-16 10:08
No I'm not asking you if you are sure you set it to 100. I am asking if the cover maybe goes to 255 like my lights do.. Or some other value.

**Comment by blackgearit** [comment] 2017-05-16 10:11
@mihalski sorry misunderstand. Yes, in cover/zwave.py the level value changes between 0 and 100.

**Comment by andrey-git** [comment] 2017-05-16 13:16
ha-themed-slider by default has max set to 100.
state-card-with-slider what uses it, sets max to 255.
Lights don't do additional overrides.
Cover makes an override to 100.

**Comment by andrey-git** [comment] 2017-05-16 13:19
@mihalski I don't know why the updated file is not loaded.
If you are comfortable with js debugger you can set a breakpoint in the sources tab to try to view the min/max values.
(Look for `console.log` that does the current printouts)

**Comment by kylerw** [comment] 2017-05-22 14:51
I'm having the same/similar issue. For me it appears to be a conflict between default 255 max brightness and my Max of 99 (based on SmartThings MQTT bridge). One is using the correct 99 value which displays differently on the other that's using the 255 max:

![image](https://cloud.githubusercontent.com/assets/370860/26314649/df752772-3ecb-11e7-80f1-c78141e5431f.png)

**Comment by andrey-git** [comment] 2017-05-22 15:06
@kylerw 
Are you using homeassistant/components/light/mqtt.py ?

HA light are *always* 0..255
If your mqtt light is 0..100 you should use `brightness_scale: 100` of the mqtt light platform.
If you are not using it, then the screenshot is working as intended: CustomUI slider is in 0..100 range because you set it so, and the more-info slider is 0..255 because light are 0..255

**Comment by kylerw** [comment] 2017-05-22 18:54
Yeah, I've got the scale in there.

customize:

      light.basement_hall_lights:
        custom_ui_state_card: custom-ui
        state_card_mode: break-slider
        stretch_slider: false
        slider_theme:
          pin: true
          max: 99
        # icon: mdi:television  

component

    - platform: mqtt
      name: "Basement Hall Lights"
      state_topic: "smartthings/Basement Hall Lights/switch"
      command_topic: "smartthings/Basement Hall Lights/switch"
      brightness_state_topic: "smartthings/Basement Hall Lights/level"
      brightness_command_topic: "smartthings/Basement Hall Lights/level"
      brightness_scale: 99
      payload_on: "on"
      payload_off: "off"
      retain: true

**Comment by andrey-git** [comment] 2017-05-22 19:22
@kylerw What is the value of brightness attribute of `light.basement_hall_lights` when the UI is in the state like in your last screenshot?

**Comment by kylerw** [comment] 2017-05-22 21:05
ok, so probably a "bug" on HA then since my assumption is the brightness_scale should also limit the slider as well.

Thanks.

**Comment by andrey-git** [comment] 2017-06-21 10:46
Closing this issue. If someone can still reproduce it - please reopen.

**Closed by andrey-git** 2017-06-21 10:46 UTC
