### ISSUE TITLE
Need to force refresh before entities show (0.53.)

### ISSUE THREAD

**Issue by laurentdinclaux** [andrey-git/home-assistant-custom-ui#45] opened 2017-09-19 09:44 UTC
I updated to 0.53 today and have empty state cards under Chrome desktop **and** mobile. 
In order to have the state cards content, I need to 
1) first open the console (F12)  
2) then force refresh (Ctrl + F5). 

**I have to do it each time I open home assistant**

Because it isn't possible to do on mobile, I cannot have it work on mobile.
Firefox has no such issue.

Looks like a duplicate of #40 

**Browser + Version:** Chrome 61

**CustomUI version:** 20170918

**Home Assistant:** 0.53.1

```
homeassistant:
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui

customizer:
  custom_ui: local
```

**Comment by tringler** [comment] 2017-09-19 09:55
I can confirm that behaviour. For mobile you can just delete cache & cookies or open it as incognito mode.

**Comment by laurentdinclaux** [comment] 2017-09-19 10:19
Do you also have to first open the console (F12) before the force refresh trick works ?

**Comment by andrey-git** [comment] 2017-09-19 10:29
On mobile, doesn't pull-down-to-refresh works?

**Comment by tringler** [comment] 2017-09-19 10:31
@laurentdinclaux - No, the force refresh is working. I don't need to open the console.
@andrey-git - No, that is not working. If I choose refresh from the chrome menu on mobile it's also not working. I need to remove cookies & cache.

**Comment by laurentdinclaux** [comment] 2017-09-19 10:49
@andrey-git nope

**Comment by laurentdinclaux** [comment] 2017-09-19 10:49
The real issue is having to do it each time I open home assistant...

**Comment by laurentdinclaux** [comment] 2017-09-19 11:00
I just noticed that when cards are loaded empty, the message "Loaded CustomUI 20170918" doesn't show up in the console. It does show on a force refresh.

I can also **toggle** between empty / non empty state cards doing F5 the ctrl + F5

**Comment by laurentdinclaux** [comment] 2017-09-19 11:14
I ended up clearing everything under Console > Application. It now works.

But it is the second time I had to do so. Last time it was to refresh some CSS because of misaligned items after an upgrade of custom ui

**Comment by pkozul** [comment] 2017-10-18 04:27
I've also noticed the same with Floorplan (as a custom state card). I need to display the Developer Tools (F12) and then press Control + F5 for the custom UI state card to actually load.

I need to do this each time I open my browser and access Home Assistant.

I think this issue is actually within the Home Assistant frontend itself, so we need to create a bug in that repo?

https://github.com/home-assistant/home-assistant-polymer/

**Comment by sumitrajancse** [comment] 2017-10-25 18:56
Confirming the same issue.. I had the same problem

**Comment by c727** [comment] 2017-10-31 11:41
@balloob suggested to change the filename each time but that's not the best solution

**Comment by andrey-git** [comment] 2017-10-31 14:07
I can't reproduce this behavior on Chrome or FF on linux.

Yes, after `state-card-cutom-ui.html` changes you need to do a hard-reload (Ctrl+F5) to pick the new file. No Dev Tools needed.

This is different for files cached by ServiceWorkers, but files loaded via `extra_html_url` are not affected by this.

There was a specific problem when upgrading from pre-0.53 to post-053 but I believe later upgrades shouldn't have the same effect.

**Comment by c727** [comment] 2017-10-31 14:54
For me Ctrl+F5 is not working in HASS without devtools and when doing it in devtools it is also not persistent.

I got it "fixed" by deleting Service Worker and Locale Storage in Cookies section now.
Again: clearing Browser cache only does not help here

**Comment by andrey-git** [comment] 2017-12-14 18:33
Closing this issue. If it persists on a recent version - please reopen.

**Closed by andrey-git** 2017-12-14 18:33 UTC
